In [5]:

# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [6]:
# Задание 1
# import numpy as np
import numpy as np
from numpy import linalg

N = 10
arr = np.flip(np.arange(N))
print(arr)



[9 8 7 6 5 4 3 2 1 0]


In [7]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [8]:
import numpy as np
new_arr = np.eye(10)
N = 10
vec = np.arange(0, N)

new = new_arr * vec #такое ли умножение?
nnew = np.flip(new) #повернуть только так адекватно смог



print(nnew) # сама матрица
print(np.sum(new)) # сумма по диагонали

#если я все правильно понял

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
45.0


In [9]:
# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [10]:
import numpy as np
from numpy import linalg


a = np.array( [[4, 2, 1],[1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

print(linalg.solve(a, b))


c = linalg.solve(a, b) 

print(a.dot(c))
# а я особо не понял ничего

[ 0.46666667  3.84444444 -5.55555556]
[ 4. 12. -3.]


In [11]:
# Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [15]:


users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """

    # длины векторов
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)
    
    return np.dot(a, b) / (aLength * bLength)


user_max = -1
max_name = 0
for ind, users in enumerate(users_stats):
  lol = cosine(users, next_user_stats)
  if lol >= user_max:
    user_max = lol
    max_name = ind

# print(cosine(users_stats[max_name], next_user_stats))

print("Наиболее похожий на пользователя next_user_stats - ", max_name, user_max)




Наиболее похожий на пользователя next_user_stats -  7 0.9486832980505138
